name: scr_flutter_technical_test_opcion_b_app
description: "Prueba técnica B"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  dart_openai: ^5.1.0
  envied: ^0.5.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  http: ^1.1.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.9
  envied_generator: ^0.5.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
